# Generated by Django 3.2.8 on 2022-02-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('payments', '0002_alter_paymentaccount_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('ADD', 'Add to balance'), ('SUB', 'Subtract from balance')], max_length=3)),
                ('amount', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_changes', to='payments.paymentaccount')),
            ],
        ),
        migrations.DeleteModel(
            name='BalanceChange',
        ),
    ]
