# Generated by Django 3.2.8 on 2022-02-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220218_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_url',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
