# Generated by Django 3.2.8 on 2022-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=260, unique=True, verbose_name='email пользователя')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный аккаунт')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Статус суперпользователя')),
                ('staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Список пользателей',
            },
        ),
    ]
