# Generated by Django 3.2.8 on 2022-02-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220218_1629'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_invoice',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.transaction'),
            preserve_default=False,
        ),
    ]
