# Generated by Django 3.2.8 on 2022-03-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskparsesubscribers',
            name='task_type',
            field=models.CharField(choices=[('FR', 'Followers'), ('FG', 'Following')], default='FR', max_length=2),
        ),
    ]
