# Generated by Django 3.2.8 on 2022-02-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220218_1629'),
        ('main', '0002_task_task_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_invoice',
        ),
        migrations.AddField(
            model_name='task',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.transaction'),
        ),
    ]
