# Generated by Django 3.2.8 on 2022-03-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_taskparsesubscribers_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskparselikes',
            name='instagram_user',
        ),
        migrations.RemoveField(
            model_name='taskparselikes',
            name='quantity_posts',
        ),
        migrations.AddField(
            model_name='taskparselikes',
            name='posts',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
