# Generated by Django 3.2.8 on 2022-02-22 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220218_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('last_use', models.DateTimeField(default=datetime.datetime(2022, 2, 22, 16, 58, 25, 457762))),
                ('in_use', models.BooleanField(default=False)),
            ],
        ),
    ]
