# Generated by Django 3.2.8 on 2022-02-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_igaccount_last_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
